### ISSUE TITLE
modrá smrt - OpenATV 5.1 (image po 12.12.2015)

### ISSUE THREAD

**Issue by uschi-cz** [mx3L/archivczsk#6]
Zdravím,

vím, že ARCHIV CZ/SK asi není primárně psaný pro OpenATV, ale až do doby někdy kolem 12.12.2015 na něm jel OK a nebyl problém. Pak přišla nějaká větší vlna aktualizací a poté každý pokus o přehrávání jakéhokoliv streamu končí modrou smrti.

Bohužel se mi nedochoval crashlog, ale byl bych určitě schopen ho dodat. Chyba končila s nějakým textem useAlternateUserAgent...

Mám DREAMBOX 800SE - originál.

Je nějaký šance, že by se povedlo s tímto něco udělat? Nevím, zda je to globální problém OpenATV 5.1 a nebo se to týká jen DM800SE. Mám tak nainstalovaný jen flashexpander, epgrefresh, csdf a mgcamd, jinak nic jiného.

Už při samotné čisté instalaci posledního image, kam jsem nahrál jen subsupport a archivcz dochází k modré smrti.

Mám dodat crashlog? Pomohlo by to něčemu?

Zdraví
Pavel

**Comment by hitman222** [comment]
U mne to same,jde s timto neco delat.
Dekuji.

**Comment by mx3L** [comment]
Poprosim o crashlog

**Comment by uschi-cz** [comment]
No, já jsem to nakonec už vyřešil... Udělal jsem čistou instalaci OPENATV bez CZSK archivu a mám to jen na sledování DVB-S2. Následně jsem zakoupil Raspberry PI2, nainstaloval KODI a CZSK Archiv plugin, který se chová mnohem lépe než na DREAMBOXu a umí některé věci navíc...

Pokud se nepletu, tak CZSK archiv je primárně vyvíjen na KODI a byl portován na ENIGMU2. Tam je asi mnohem horší zachovat funkčnost na různých verzích/vydavatelích image. OPENPLI mě neoslovilo. Chtěl jsem mít OPENATV a také CZSK archiv = pro každé jedna krabička a jedna komunita :-)

@hitman222 dodáš crashlog? Pokud ne, tak nemám problém to udělat, stačí říct... :-D

Dále chci poděkovat mx3L za velmi dobrou práci na tomto pluginu díky kterému je v televizi opravdu na co se dívat! Dobrá práce!

**Comment by hitman222** [comment]
Ahoj,crashlog nemozem urobit,v atv to asi nefunguje a neviem kam sa ulozi
crashlog pri pade archivu.
To atv je divne.Pada to na kazdej verzii co som nainstaloval.
Postup na crashlog mam od teba tento:

1. init 4; - vypne e2, pricom sa automaticky nenastartuje
2. enigma2 > /tmp/e2.log 2>&1 - zapne e2 a zacne zapisovat log do
/tmp/e2.log
3. Otvor MP2 nacitaj nejake video s titulkami, skus dat zmenit kodovanie,
pre overenie skus to iste este na nejakom inom videu s titulkami
4. killall enigma2 - vypne e2 a vytvaranie logu
5. init 3 - zapne e2 a jej automaticke startovanie po vypnuti
6. posli sem /tmp/e2.log

2016-01-12 18:46 GMT+01:00 mx3L <notifications@github.com>:

**Comment by hitman222** [comment]
Keby si mohol tak urob,mne to nejde. Dik

Dne 12. ledna 2016 19:42 uschi-cz <notifications@github.com> napsal(a):

**Comment by mx3L** [comment]
Crashlog sa vytvori automaticky pri pade enigmy

Ak mas mountnuty hdd tak by mal byt tam:
`/media/hdd/enigma2_crashlog..`
ak nie tak skus pozriet
`/home/root/enigma2_crashlog..`
alebo
`/tmp/enigma2_crashlog..`

**Comment by hitman222** [comment]
Tak tady je.

Dne 12. ledna 2016 19:42 uschi-cz <notifications@github.com> napsal(a):

**Comment by hitman222** [comment]
Tak este jeden to bol spatny.

Dne 12. ledna 2016 19:42 uschi-cz <notifications@github.com> napsal(a):

**Comment by uschi-cz** [comment]
V ATV je to /home/root/enigma2_crashlog...

Co se ATV 5.1 nebo 4.2 verze týče, tak poslední verze IMAGE kde mi jel CZSK archiv vyšla tuším 11.12.2015. Když jsem si nainstaloval jakýkoliv novější verzi, tak okamžitě modrá smrt.

Pokud je crashlog OK, tak už nebudu asi dělat nic :-) Pokud ne, tak nainstaluji, vygeneruji :-)

**Comment by hitman222** [comment]
No mne to robilo aj na verzii este starsej myslim september.

**Comment by mx3L** [comment]
Kde mozem najst ten crashlog?

**Comment by uschi-cz** [comment]
No jo, on asi vlastně nebyl vložen...

@hitman222 já to registroval až v prosinci. Září si moc nepamatuji, ale nejsem si vědom nějakých crashů.

**Comment by hitman222** [comment]
Poslal som na email co mi prisiel.
Daj email a preposlem.

2016-01-12 21:14 GMT+01:00 mx3L <notifications@github.com>:

**Comment by mx3L** [comment]
mx3Lmail@gmail.com

**Comment by uschi-cz** [comment]
Lze ho vložit drag n drop do textového pole kam píšeš :-)

**Comment by mx3L** [comment]
Diky pripinam sem:
```
ctionA KEY: 108 0 KEY_DOWN DOWN
20:24:58.501 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
20:24:58.502 [   ] driver/rcinput.cpp:23 handleCode 0 6c 1
20:24:58.505 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 1 KEY_DOWN DOWN
20:24:59.233 [   ] driver/rcinput.cpp:23 handleCode 1 160 1
20:24:59.236 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 0 KEY_OK OK
20:24:59.238 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions ok
20:24:59.240 { E } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: [VideoAddonItemHandler] cannot handle <PCategory - Video doplÅˆky>
20:24:59.241 { E } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: [CategoryVideoAddonItemHandler] cannot handle <PCategory - Video doplÅˆky>
20:24:59.242 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: found handler [CategoryItemHandler]
20:24:59.277 {   } Plugins/Extensions/archivCZSK/gui/common.py:400 setText 17 -12
20:24:59.530 [   ] driver/rcinput.cpp:23 handleCode 0 160 1
20:24:59.533 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 1 KEY_OK OK
20:24:59.885 [   ] driver/rcinput.cpp:23 handleCode 1 6c 1
20:24:59.888 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 0 KEY_DOWN DOWN
20:24:59.889 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
20:25:00.056 [   ] driver/rcinput.cpp:23 handleCode 0 6c 1
20:25:00.059 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 1 KEY_DOWN DOWN
20:25:00.240 [   ] driver/rcinput.cpp:23 handleCode 1 6c 1
20:25:00.244 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 0 KEY_DOWN DOWN
20:25:00.245 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
20:25:00.411 [   ] driver/rcinput.cpp:23 handleCode 0 6c 1
20:25:00.415 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 1 KEY_DOWN DOWN
20:25:00.620 [   ] driver/rcinput.cpp:23 handleCode 1 6c 1
20:25:00.624 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 0 KEY_DOWN DOWN
20:25:00.626 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
20:25:00.791 [   ] driver/rcinput.cpp:23 handleCode 0 6c 1
20:25:00.795 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 1 KEY_DOWN DOWN
20:25:01.001 [   ] driver/rcinput.cpp:23 handleCode 1 6c 1
20:25:01.004 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 0 KEY_DOWN DOWN
20:25:01.006 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
20:25:01.200 [   ] driver/rcinput.cpp:23 handleCode 0 6c 1
20:25:01.203 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 1 KEY_DOWN DOWN
20:25:01.550 [   ] driver/rcinput.cpp:23 handleCode 1 160 1
20:25:01.553 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 0 KEY_OK OK
20:25:01.554 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions ok
20:25:01.556 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: found handler [VideoAddonItemHandler]
20:25:01.560 {   } Screens/Screen.py:150 show [SCREENNAME]  LoadingScreen
20:25:01.569 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: trying to resolve dependencies for VideoAddon(SosÃ¡Ä 1.2.2)
20:25:01.570 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: VideoAddon(SosÃ¡Ä 1.2.2) requires script.module.stream.resolver addon, version 1.6.25
20:25:01.571 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: required ToolsAddon(stream resolver 1.6.33) founded
20:25:01.573 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: [VideoAddonContentProvider] started
20:25:01.591 {   } Plugins/Extensions/archivCZSK/engine/contentprovider.py:31 append [AddonSysPath] append /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib
20:25:01.890 [   ] driver/rcinput.cpp:23 handleCode 0 160 1
20:25:01.906 {   } Plugins/Extensions/archivCZSK/engine/contentprovider.py:31 append [AddonSysPath] append /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider
20:25:01.907 {   } Plugins/Extensions/archivCZSK/engine/contentprovider.py:31 append [AddonSysPath] append /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto
20:25:01.914 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 1 KEY_OK OK
20:25:02.148 {   } Plugins/Extensions/archivCZSK/engine/contentprovider.py:31 append [AddonSysPath] append /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server
20:25:03.026 {   } <string>:25 <module> Using dummy storage server
20:25:03.182 {   } Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/default.py:40 <module> ('Running sosac provider with params:', {})
20:25:03.259 {   } Plugins/Extensions/archivCZSK/gui/content.py:170 resolveCommand {}
20:25:03.272 {   } skin.py:847 readSkin [SKIN] Parsing embedded skin <embedded-in-'LoadingScreen'>
20:25:03.275 {   } skin.py:1034 readSkin [SKIN] processing screen <embedded-in-'LoadingScreen'>:
20:25:03.285 {   } Plugins/Extensions/archivCZSK/gui/common.py:400 setText 3 9999
20:25:03.310 {   } skin.py:847 readSkin [SKIN] Parsing embedded skin <embedded-in-'ContentScreen'>
20:25:03.314 {   } skin.py:1034 readSkin [SKIN] processing screen <embedded-in-'ContentScreen'>:
20:25:03.345 {   } Plugins/Extensions/archivCZSK/gui/common.py:384 applySkin 1998 / 204 = 9.79411764706
20:25:03.345 {   } Plugins/Extensions/archivCZSK/gui/common.py:385 applySkin 870
20:25:03.346 {   } Plugins/Extensions/archivCZSK/gui/common.py:388 applySkin 88
20:25:03.347 { W } Components/GUISkin.py:35 createGUIScreen warning, skin is missing element path_label in <class 'Plugins.Extensions.archivCZSK.gui.content.ContentScreen'>
20:25:03.355 { W } Components/GUISkin.py:35 createGUIScreen warning, skin is missing element path_pixmap in <class 'Plugins.Extensions.archivCZSK.gui.content.ContentScreen'>
20:25:03.389 {   } skin.py:1034 readSkin [SKIN] processing screen SimpleSummary:
20:25:03.412 {   } Screens/Screen.py:150 show [SCREENNAME]  ['ContentScreen_summary', 'SimpleSummary']
20:25:03.426 {   } Screens/Screen.py:150 show [SCREENNAME]  ContentScreen
20:25:04.098 [   ] driver/rcinput.cpp:23 handleCode 1 6c 1
20:25:04.101 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 0 KEY_DOWN DOWN
20:25:04.103 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
20:25:04.269 [   ] driver/rcinput.cpp:23 handleCode 0 6c 1
20:25:04.272 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 1 KEY_DOWN DOWN
20:25:05.963 [   ] driver/rcinput.cpp:23 handleCode 1 190 1
20:25:05.967 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 400 0 KEY_YELLOW YELLOW
20:25:05.968 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions yellow
20:25:06.015 {   } skin.py:847 readSkin [SKIN] Parsing embedded skin <embedded-in-'ShortcutsScreen'>
20:25:06.018 {   } skin.py:1034 readSkin [SKIN] processing screen <embedded-in-'ShortcutsScreen'>:
20:25:06.054 {   } skin.py:1034 readSkin [SKIN] processing screen SimpleSummary:
20:25:06.077 {   } Screens/Screen.py:150 show [SCREENNAME]  ['ShortcutsScreen_summary', 'SimpleSummary']
20:25:06.090 {   } Screens/Screen.py:150 show [SCREENNAME]  ShortcutsScreen
20:25:06.139 [   ] driver/rcinput.cpp:23 handleCode 0 190 1
20:25:06.143 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 400 1 KEY_YELLOW YELLOW
20:25:07.866 [   ] driver/rcinput.cpp:23 handleCode 1 160 1
20:25:07.869 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 0 KEY_OK OK
20:25:07.871 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions ok
20:25:07.879 {   } Screens/Screen.py:150 show [SCREENNAME]  ['ContentScreen_summary', 'SimpleSummary']
20:25:07.899 {   } Screens/Screen.py:150 show [SCREENNAME]  ContentScreen
20:25:07.903 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: found handler [FolderItemHandler]
20:25:07.907 {   } Screens/Screen.py:150 show [SCREENNAME]  LoadingScreen
20:25:07.929 {   } Plugins/Extensions/archivCZSK/engine/contentprovider.py:31 append [AddonSysPath] append /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib
20:25:07.934 {   } Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/default.py:40 <module> ('Running sosac provider with params:', {'cp': 'sosac.ph', 'list': '#tvshow#http://tv.prehraj.me/cs/detail/arrow'})
20:25:07.956 {   } <string>:154 list ('Examining url', '#tvshow#http://tv.prehraj.me/cs/detail/arrow')
20:25:08.163 [   ] driver/rcinput.cpp:23 handleCode 0 160 1
20:25:08.166 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 1 KEY_OK OK
20:25:09.205 {   } Plugins/Extensions/archivCZSK/gui/common.py:400 setText 8 88
20:25:10.954 [   ] driver/rcinput.cpp:23 handleCode 1 6c 1
20:25:10.957 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 0 KEY_DOWN DOWN
20:25:10.959 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
20:25:11.125 [   ] driver/rcinput.cpp:23 handleCode 0 6c 1
20:25:11.128 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 108 1 KEY_DOWN DOWN
20:25:11.552 [   ] driver/rcinput.cpp:23 handleCode 1 160 1
20:25:11.555 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 0 KEY_OK OK
20:25:11.556 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions ok
20:25:11.558 { E } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: [FolderItemHandler] cannot handle <PVideoNotResolved - Å˜ada 1 Epizoda 1  - Pilot>
20:25:11.559 { E } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: [VideoResolvedItemHandler] cannot handle <PVideoNotResolved - Å˜ada 1 Epizoda 1  - Pilot>
20:25:11.561 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: found handler [VideoNotResolvedItemHandler]
20:25:11.564 {   } Screens/Screen.py:150 show [SCREENNAME]  LoadingScreen
20:25:11.584 {   } Plugins/Extensions/archivCZSK/engine/contentprovider.py:31 append [AddonSysPath] append /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib
20:25:11.589 {   } Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/default.py:40 <module> ('Running sosac provider with params:', {'play': 'http://tv.prehraj.me/cs/player/arrow-s1-e01', 'cp': 'sosac.ph', 'title': '\xc5\x98ada 1 Epizoda 1  - Pilot'})
20:25:11.849 [   ] driver/rcinput.cpp:23 handleCode 0 160 1
20:25:11.852 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 1 KEY_OK OK
20:25:12.055 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: xbmc_doplnky: info ['Found resolvable http://www.streamuj.tv/video/f587642ab0c69a1adcb5?remote=1&affid=0&width=960&height=525']
20:25:12.057 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: xbmc_doplnky: info [u'Resolving http://www.streamuj.tv/video/f587642ab0c69a1adcb5?remote=1&affid=0&width=960&height=525']
20:25:12.503 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: xbmc_doplnky: info ["Using resolver 'streamujtv'"]
20:25:13.923 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: xbmc_doplnky: info ['filtering by quality setting 0']
20:25:13.944 {   } skin.py:847 readSkin [SKIN] Parsing embedded skin <embedded-in-'SelectSource'>
20:25:13.947 {   } skin.py:1034 readSkin [SKIN] processing screen <embedded-in-'SelectSource'>:
20:25:13.958 { W } Components/GUISkin.py:35 createGUIScreen warning, skin is missing element item_pixmap in <class 'Plugins.Extensions.archivCZSK.gui.context.SelectSource'>
20:25:13.969 {   } skin.py:1034 readSkin [SKIN] processing screen SimpleSummary:
20:25:13.991 {   } Screens/Screen.py:150 show [SCREENNAME]  ['SelectSource_summary', 'SimpleSummary']
20:25:14.003 {   } Screens/Screen.py:150 show [SCREENNAME]  SelectSource
20:25:15.401 [   ] driver/rcinput.cpp:23 handleCode 1 160 1
20:25:15.405 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 352 0 KEY_OK OK
20:25:15.406 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions ok
20:25:15.413 {   } Screens/Screen.py:150 show [SCREENNAME]  ['ContentScreen_summary', 'SimpleSummary']
20:25:15.431 {   } Screens/Screen.py:150 show [SCREENNAME]  ContentScreen
20:25:15.435 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: [VideoAddonContentProvider] paused
20:25:15.440 [   ] dvb/cahandler.cpp:329 unregisterService [eDVBCAService] free slot 0 demux 0 for service 1:0:1:105:F01:20CB:EEEE0000:0:0:0:
20:25:15.440 [   ] dvb/cahandler.cpp:474 ~eDVBCAService [eDVBCAService] free service 1:0:1:105:F01:20CB:EEEE0000:0:0:0:
20:25:15.464 [   ] dvb/decoder.cpp:815 setState decoder state: play, vpid=-1, apid=-1, pcrpid=-1
20:25:15.465 <   > dvb/decoder.cpp:710 stop DEMUX_STOP - pcr - ok
20:25:15.466 <   > dvb/decoder.cpp:413 stop DEMUX_STOP - video - ok
20:25:15.484 <   > dvb/decoder.cpp:422 stop VIDEO_STOP - ok
20:25:15.485 <   > dvb/decoder.cpp:157 stop AUDIO_STOP - ok
20:25:15.487 <   > dvb/decoder.cpp:165 stop DEMUX_STOP - audio - ok
20:25:15.489 <   > dvb/decoder.cpp:201 unfreeze AUDIO_CONTINUE - ok
20:25:15.497 [   ] dvb/dvb.cpp:1254 DVBChannelStateChanged start release channel timer
20:25:15.500 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: Loading CustomVideoPlaySetting
20:25:15.502 {   } Plugins/Extensions/archivCZSK/__init__.py:52 info [ArchivCZSK] INFO: [VideoAddonContentProvider] resumed
20:25:15.503 { D } Traceback (most recent call last):
20:25:15.504 { D }   File "/usr/lib/enigma2/python/mytest.py", line 227, in processDelay
20:25:15.509 { D }     callback(*retval)
20:25:15.510 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/handlers/media.py", line 118, in selected_source
20:25:15.513 { D }     callback(item)
20:25:15.514 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/handlers/media.py", line 101, in wrapped
20:25:15.516 { D }     MediaItemHandler.play_item(self, res_item, mode)
20:25:15.516 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/handlers/media.py", line 36, in play_item
20:25:15.517 { D }     start_play(item, mode)
20:25:15.518 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/exception.py", line 122, in wrapped
20:25:15.521 { D }     func(*args, **kwargs) 
20:25:15.522 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/handlers/media.py", line 31, in start_play
20:25:15.522 { D }     self.content_provider.play(self.session, item, mode, end_play)
20:25:15.523 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py", line 168, in play
20:25:15.527 { D }     self.player.play()
20:25:15.528 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/player/player.py", line 758, in play
20:25:15.536 { D }     self._playStream(srefName, playUrl, subtitlesUrl, verifyLink=verifyLink)
20:25:15.537 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/player/player.py", line 845, in _playStream
20:25:15.543 { D }     playAndDownloadGst)
20:25:15.543 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/player/setting.py", line 18, in loadSettings
20:25:15.546 { D }     CustomVideoPlaySetting(userAgent, extraHeaders, downloadMode)
20:25:15.547 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/player/setting.py", line 68, in __init__
20:25:15.548 { D }     self.vpsp.setUserAgent(userAgent)
20:25:15.549 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/player/setting.py", line 51, in setUserAgent
20:25:15.550 { D }     config.mediaplayer.useAlternateUserAgent.setValue(False)
20:25:15.550 { D }   File "/usr/lib/enigma2/python/Components/config.py", line 1777, in __getattr__
20:25:15.552 { D } KeyError: 'useAlternateUserAgent'
20:25:15.552 [ E ] python/python.cpp:209 call (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session instance at 0x742412d8>>,()) failed)
]]>
```

**Comment by uschi-cz** [comment]
!!! To je přesně ono, pamatoval jsem si to usAlternateUserAgent, že bylo na konci... Viděl jsem, že problém je v player, tak jsem zkoušel instalovat mediaplayer2, změnit player v nastavení archivů, ale nepomohlo nic. Google byl též skoupí na slovo...

**Comment by mx3L** [comment]
Zvlastne, nemalo by sa to stat.
 
Skuste opravu:
https://dl.dropboxusercontent.com/u/38760017/enigma2-plugin-extensions-archivczsk_0.72_beta_6_20151129_all.ipk

**Comment by hitman222** [comment]
Super vyborna a rychla robota ako vzdy.
Dakujem moc.

2016-01-12 21:54 GMT+01:00 mx3L <notifications@github.com>:

**Comment by mx3L** [comment]
Vdaka za info, pridam novu veziu..

**Comment by mx3L** [comment]
Opravene v 0.72-beta.7
