### ISSUE TITLE
Nefunkcny archiv stream cinema czsk

### ISSUE THREAD

**Issue by baaluu** [mx3L/archivczsk#66]
Od vcera nefunguje archiv ze Nepodarilo sa nacitat hlavne menu - chyba pripojenia.Mam Openatv 6,1 no nejde ani na Openatv 6,0,Mam premium VIP.

**Comment by kaffi1972** [comment]
Pripájam sa . . . nejde ani v openpli . . .

**Comment by kaffi1972** [comment]
Dúfam, že to admin čím skor opravý . . . tiež mám zaplatený VIP účet.

**Comment by noman256** [comment]
Mam pocit, ze je tohle spatne misto na stezovani na stream cinema modul, ale i tak sem dam log. :)

11:19:55.948 [INFO] StaticDataSC init...
11:19:56.559 [ERROR] Chyba pripojenia.
Traceback (most recent call last):
  File "<string>", line 402, in _json
  File "<string>", line 228, in wrap
  File "<string>", line 12, in cacheFunction
  File "<string>", line 392, in get_data_cached
  File "<string>", line 78, in request
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Temporarily Unavailable

11:25:37.385 [INFO] StaticDataSC init...
11:25:38.112 [ERROR] Chyba pripojenia.
Traceback (most recent call last):
  File "<string>", line 402, in _json
  File "<string>", line 228, in wrap
  File "<string>", line 12, in cacheFunction
  File "<string>", line 392, in get_data_cached
  File "<string>", line 78, in request
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Comment by noman256** [comment]
Tady je spravny hrobecek kde se ma plakat :) https://github.com/bbaronSVK/plugin.video.stream-cinema/issues

**Comment by baaluu** [comment]
Uz to ide !!!

**Comment by noman256** [comment]
Tak to zavri baaluu ;)
