### ISSUE TITLE
VTI 13.0.3 a SC 1.2.5 crash

### ISSUE THREAD

**Issue by vatlach** [mx3L/archivczsk#70]
Niekedy sposobi crash.Log:
[ArchivCZSK] INFO:   VideoAddonContentProvider(VideoAddon(Stream Cinema-1.2.5)) get_content_cb - success: False, items: 0, guicmd: None - {}
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/task.py", line 31, in run_in_main_thread
    fnc_out_queue.get()()
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/task.py", line 168, in wrapped_finish
    self.callback(success, result)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py", line 747, in _get_content_cb
    self.content_deferred.errback(result)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 494, in _startRunCallbacks
twisted.internet.defer.AlreadyCalledError
(PyObject_CallObject(<function run_in_main_thread at 0x8e6dfab0>,(0,)) failed)
]]>

**Comment by mtester270** [comment]
Ak chces nieco poriesit tak zapnuty mod=ladenie a poprosim archivczsk.log a streamcinema.log

A aspon malicky popis co si robil ked to spadlo nezaskodi... 

Takze zatvaram
