### ISSUE TITLE
Pomale menu

### ISSUE THREAD

**Issue by pmisun** [mx3L/archivczsk#79]
Ahoj, pred cca mesiacom som na popud zeny zaregistroval ze nacitanie menu v sosaci ale i inych sluzbach je extremne pomale. Odskusane na technet img vti, classic vti, rovnako sa chova i v aktualne preferovanom image openatv 6.1

Neviete mi poradit kde moze byt problem? Nastavenia som skusal vypnut info o filme, znizit buffer z 10 na 7...nic nepomohlo.

**Comment by pmisun** [comment]
00:58:41.143 [INFO] Checking archivCZSK update...
00:58:41.849 [INFO] Checking addons update...
00:59:07.182 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/content.py", line 798, in getPosterImage
    download_web_file(url, videoPoster)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/util.py", line 209, in download_web_file
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 422, in open
  File "/usr/lib/python2.7/urllib2.py", line 284, in get_type
ValueError: unknown url type: None

01:01:08.012 [INFO] Checking archivCZSK update...
01:01:08.639 [INFO] Checking addons update...
01:02:25.831 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/content.py", line 798, in getPosterImage
    download_web_file(url, videoPoster)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/util.py", line 209, in download_web_file
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 468, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 655, in http_error_302
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 474, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 557, in http_error_default
HTTPError: HTTP Error 500: Internal Server Error

01:02:37.902 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/content.py", line 798, in getPosterImage
    download_web_file(url, videoPoster)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/util.py", line 209, in download_web_file
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 468, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 655, in http_error_302
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 474, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 557, in http_error_default
HTTPError: HTTP Error 500: Internal Server Error

01:02:50.237 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/content.py", line 798, in getPosterImage
    download_web_file(url, videoPoster)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/util.py", line 209, in download_web_file
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 468, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 655, in http_error_302
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 474, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 557, in http_error_default
HTTPError: HTTP Error 500: Internal Server Error

01:04:05.945 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/content.py", line 798, in getPosterImage
    download_web_file(url, videoPoster)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/util.py", line 209, in download_web_file
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 468, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 655, in http_error_302
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 474, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 557, in http_error_default
HTTPError: HTTP Error 500: Internal Server Error

01:04:18.096 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/content.py", line 798, in getPosterImage
    download_web_file(url, videoPoster)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/util.py", line 209, in download_web_file
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 468, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 655, in http_error_302
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 474, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 557, in http_error_default
HTTPError: HTTP Error 500: Internal Server Error

01:08:16.432 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/content.py", line 798, in getPosterImage
    download_web_file(url, videoPoster)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/util.py", line 209, in download_web_file
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 468, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 655, in http_error_302
  File "/usr/lib/python2.7/urllib2.py", line 436, in open
  File "/usr/lib/python2.7/urllib2.py", line 549, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 474, in error
  File "/usr/lib/python2.7/urllib2.py", line 408, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 557, in http_error_default
HTTPError: HTTP Error 500: Internal Server Error

01:08:16.480 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/content.py", line 798, in getPosterImage
    download_web_file(url, videoPoster)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/util.py", line 209, in download_web_file
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 422, in open
  File "/usr/lib/python2.7/urllib2.py", line 284, in get_type
ValueError: unknown url type: None

**Comment by mtester270** [comment]
Ak si vypol info o filme tak nie je mozne aby si mal takyto LOG. Co sa tyka tvojho problemu tak by som to videl na kontakt tvojho internetoveho poskytovatela. Vsetko ide standardne ako ma.
